### ISSUE TITLE
イメージ画像をREADME.mdに追加しません！？

### ISSUE THREAD

**Issue by hashy0917** [ShinkoLab/x210-24GT-Rackmount-3D#1]
![PXL_20210627_061533789](https://user-images.githubusercontent.com/19991619/124297339-ee53a000-db95-11eb-9e83-a1957f374501.jpg)

**Comment by hashy0917** [comment]
`![PXL_20210627_061533789](https://user-images.githubusercontent.com/19991619/124297339-ee53a000-db95-11eb-9e83-a1957f374501.jpg)` 
↑をREADME.mdのどこかに張り付けていただければOKです！

**Comment by hashy0917** [comment]
![PXL_20210626_081625239](https://user-images.githubusercontent.com/19991619/124297643-3e326700-db96-11eb-84ce-8923eeaa6a68.jpg)
![PXL_20210626_131713266](https://user-images.githubusercontent.com/19991619/124297651-3f639400-db96-11eb-8c1d-6fdf7d4068ac.jpg)

`![PXL_20210626_081625239](https://user-images.githubusercontent.com/19991619/124297643-3e326700-db96-11eb-84ce-8923eeaa6a68.jpg)`

`![PXL_20210626_131713266](https://user-images.githubusercontent.com/19991619/124297651-3f639400-db96-11eb-8c1d-6fdf7d4068ac.jpg)`

**Comment by ShinkoLab** [comment]
追加しました！
わざわざ画像の準備までありがとうございます。
